### ISSUE TITLE
Icon issue (FYI)

### ISSUE THREAD

**Issue by lin-ycv** [ohroy/Community.PowerToys.Run.Plugin.Everything#1]
Hi rozbo,

This is not an issue, but more of a FYI.

The method you're currently using to get file icons will cause PTR to temporary freeze when searching for non-local files (ie: Google drive/One Drive files that's online only)
https://github.com/rozbo/Community.PowerToys.Run.Plugin.Everything/blob/bb047f9bd126c9a7ff11b4efe4da97e41525ba39/src/Main.cs#L112

this is because the file will have to be partially download to provide the icon info, depending on the user's internet speed, it may or may not be an issue.

On a side note, I have a similar plugin ([Everything for PowerToys Run](https://github.com/lin-ycv/EverythingPowerToys)). Where I'm trying to solve this, by searching the registry to find the icon of the local program that's associated with the file extension type. But it's creating other problems that I'm currently solving.

**Comment by ohroy** [comment]
您好，这个插件是我从 [WOX](https://github.com/Wox-launcher/Wox/tree/master/Plugins/Wox.Plugin.Everything/Everything)移植而来，只是修正了与PT的兼容性，以此来实验作为第三方插件的可能性（[详情在这里](https://github.com/microsoft/PowerToys/pull/18437)），说实话逻辑方面暂时还没研究。。


感谢您为社区做出的贡献！
